name: down_bias_chaser_careful_tight_tp095_cheap0005_balstok30
type: rule_based
starting_balance: 100
order_usd: 1

params:
  default_usd_amount: 1
  max_orders: 28
  cooldown_ticks: 8

  rules:
    - name: take_profit_up_position
      all:
        - metric: has_up_position
          operator: "is"
          value: true
        - metric: up_price
          operator: ">="
          value: 0.95
      action: sell_up

    - name: take_profit_down_position
      all:
        - metric: has_down_position
          operator: "is"
          value: true
        - metric: down_price
          operator: ">="
          value: 0.95
      action: sell_down

    - name: cheap_up_optional_lottery
      all:
        - metric: up_price
          operator: "<="
          value: 0.005
      action: buy_up
      balance_scaled_token_amount: 30

    - name: cheap_down_down_bias_lottery
      all:
        - metric: down_price
          operator: "<="
          value: 0.005
      action: buy_down
      balance_scaled_token_amount: 30

    - name: btc_below_price_to_beat_buy_down
      all:
        - metric: btc_below_price_to_beat
          operator: "is"
          value: true
        - metric: down_price
          operator: "<="
          value: 0.7
      action: buy_down
      balance_scaled_token_amount: 30

    - name: up_price_momentum_chase_buy_up
      all:
        - metric: up_price_pct_change
          operator: ">="
          value: 5
        - metric: up_price
          operator: "<="
          value: 0.7
      action: buy_up
      balance_scaled_token_amount: 30

    - name: down_price_momentum_chase_buy_down
      all:
        - metric: down_price_pct_change
          operator: ">="
          value: 5
        - metric: down_price
          operator: "<="
          value: 0.7
      action: buy_down
      balance_scaled_token_amount: 30
