name: down_bias_fader_tp0925_cheap005_tok1
type: rule_based
starting_balance: 100
order_usd: 1

params:
  default_usd_amount: 1
  max_orders: 55
  cooldown_ticks: 5

  rules:
    - name: take_profit_up_position
      all:
        - metric: has_up_position
          operator: "is"
          value: true
        - metric: up_price
          operator: ">="
          value: 0.925
      action: sell_up

    - name: take_profit_down_position
      all:
        - metric: has_down_position
          operator: "is"
          value: true
        - metric: down_price
          operator: ">="
          value: 0.925
      action: sell_down

    - name: cheap_up_optional_lottery
      all:
        - metric: up_price
          operator: "<="
          value: 0.05
      action: buy_up
      token_amount: 1

    - name: cheap_down_down_bias_lottery
      all:
        - metric: down_price
          operator: "<="
          value: 0.05
      action: buy_down
      token_amount: 2

    - name: btc_below_price_to_beat_buy_down
      all:
        - metric: btc_below_price_to_beat
          operator: "is"
          value: true
        - metric: down_price
          operator: "<="
          value: 0.9
      action: buy_down
      token_amount: 2

    - name: fade_up_price_spike_buy_down
      all:
        - metric: up_price_pct_change
          operator: ">="
          value: 5
        - metric: up_price
          operator: ">="
          value: 0.6
      action: buy_down
      token_amount: 2

    - name: fade_down_price_spike_buy_up
      all:
        - metric: down_price_pct_change
          operator: ">="
          value: 5
        - metric: down_price
          operator: ">="
          value: 0.6
      action: buy_up
      token_amount: 1
