name: rule_price_momentum
type: rule_based
starting_balance: 100
order_usd: 1

params:
  default_usd_amount: 1
  max_orders: 50
  cooldown_ticks: 3

  rules:
    - name: up_price_momentum_buy_up
      all:
        - metric: up_price_pct_change
          operator: ">="
          value: 3
        - metric: up_price
          operator: "<="
          value: 0.85
      action: buy_up
      usd_amount: 2

    - name: down_price_momentum_buy_down
      all:
        - metric: down_price_pct_change
          operator: ">="
          value: 3
        - metric: down_price
          operator: "<="
          value: 0.85
      action: buy_down
      usd_amount: 2

