name: family_cheap_lottery_only
type: rule_based
starting_balance: 100
order_usd: 1

params:
  default_usd_amount: 1
  max_orders: 65
  cooldown_ticks: 3

  rules:
    - name: take_profit_up_position
      all:
        - metric: has_up_position
          operator: "is"
          value: true
        - metric: up_price
          operator: ">="
          value: 0.95
      action: sell_up

    - name: take_profit_down_position
      all:
        - metric: has_down_position
          operator: "is"
          value: true
        - metric: down_price
          operator: ">="
          value: 0.95
      action: sell_down

    - name: cheap_up_lottery
      all:
        - metric: up_price
          operator: "<="
          value: 0.025
      action: buy_up
      token_amount: 25

    - name: cheap_down_lottery
      all:
        - metric: down_price
          operator: "<="
          value: 0.025
      action: buy_down
      token_amount: 25
